name: "🐛 Bug Report"
description: Create a new issue for a bug report.
title: "🐛 [BUG] - <title>"
labels: [
  "Bug",
  "New Issue"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Clear and concise description of your issue...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If possible, attach screenshots to help demonstrate your issue.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output, if any. 
      render: bash
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: In what OS does the bug occur?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false