name: "⭐ Enhancement Request"
description: Create a new issue for a new enhancement request.
title: "<title>"
labels: [
  "Enhancement",
  "New Issue"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the request
      placeholder: Describe your request.
    validations:
      required: true
  - type: textarea
    id: reasonings
    attributes:
      label: "Reasonings"
      description: Provide reasons why your request should be taken into account
      placeholder: Supply purposes and meaningfulness of your request.
    validations:
      required: true